import { Node, Edge } from 'reactflow';
import { NodeType, NodeData } from '../types';

export const generatePythonCode = (nodes: Node<NodeData>[], edges: Edge[]): string => {
  // Topological sort to determine execution order
  const sortedNodes: Node<NodeData>[] = [];
  const visited = new Set<string>();
  const visiting = new Set<string>();

  const visit = (nodeId: string) => {
    if (visiting.has(nodeId)) return; // Cycle detected or already processing
    if (visited.has(nodeId)) return;

    visiting.add(nodeId);

    // Find dependencies (nodes that connect TO this node)
    const incomingEdges = edges.filter(e => e.target === nodeId);
    incomingEdges.forEach(edge => {
      visit(edge.source);
    });

    visiting.delete(nodeId);
    visited.add(nodeId);
    const node = nodes.find(n => n.id === nodeId);
    if (node) sortedNodes.push(node);
  };

  nodes.forEach(node => visit(node.id));

  let code = `import os
import json
import requests
import google.generativeai as genai

# -------------------------------------------------------------------------
# Generated by FlowGen AI
# Make sure to install dependencies:
# pip install google-generativeai requests
# 
# Set your API key in the environment variables:
# export GEMINI_API_KEY="your_api_key_here"
# -------------------------------------------------------------------------

# Configure API Key
genai.configure(api_key=os.getenv("GEMINI_API_KEY"))

def get_nested_value(data, path):
    """Helper to safely get nested values like 'user.name'"""
    try:
        return reduce(lambda d, k: d[k], path.split('.'), data)
    except:
        return None

from functools import reduce

def run_workflow():
    results = {}
    print("🚀 Starting Workflow Execution...")
`;

  sortedNodes.forEach(node => {
    // Sanitize ID for python variable names
    const safeId = node.id.replace(/[-]/g, '_');
    const label = node.data.label;
    const config = node.data.config || {};

    // Find input source
    const incomingEdge = edges.find(e => e.target === node.id);
    const sourceId = incomingEdge ? incomingEdge.source.replace(/[-]/g, '_') : null;
    const inputVar = sourceId ? `results['${sourceId}']` : '{}';

    code += `
    # ----------------------------------------
    # Node: ${label}
    # Type: ${node.data.type}
    # ----------------------------------------
    try:
        input_data = ${inputVar}
`;

    switch (node.data.type) {
      case NodeType.WEBHOOK:
        const mockData = config.mockData ? config.mockData.replace(/"/g, '\\"') : '{}';
        // JSON.parse logic in python
        code += `        # Webhook acts as a trigger with mock data
        mock_json = """${config.mockData || '{}'}"""
        output = json.loads(mock_json)
`;
        break;

      case NodeType.AI_AGENT:
        const prompt = config.prompt ? config.prompt.replace(/"/g, '\\"') : '';
        const model = config.model || 'gemini-2.5-flash';
        code += `        # Gemini AI Generation
        model = genai.GenerativeModel('${model}')
        base_prompt = """${prompt}"""
        
        # Combine prompt with previous input context
        full_prompt = f"{base_prompt}\\n\\nInput Context:\\n{json.dumps(input_data, indent=2)}"
        
        response = model.generate_content(full_prompt)
        output = {"text": response.text}
`;
        break;
        
      case NodeType.CONDITION:
          const variable = config.variable || '';
          const operator = config.operator || 'equals';
          const value = config.value || '';
          
          let opSymbol = '==';
          if (operator === 'not_equals') opSymbol = '!=';
          if (operator === 'greater_than') opSymbol = '>';
          if (operator === 'less_than') opSymbol = '<';
          
          code += `        # Conditional Logic
        variable_name = "${variable}"
        check_value = get_nested_value(input_data, variable_name)
        
        condition_result = False
        
        # Determine value type for comparison
        target_value = "${value}"
        # Try to cast target value to number if possible for numeric comparisons
        try:
            if "." in target_value:
                target_value = float(target_value)
            else:
                target_value = int(target_value)
        except:
            pass
            
        if "${operator}" == "contains":
            condition_result = str(target_value).lower() in str(check_value).lower()
        else:
            try:
                condition_result = check_value ${opSymbol} target_value
            except:
                condition_result = False
                
        output = input_data # Pass input forward
        print(f"   👉 Condition {variable_name} (${operator} {value}) = {condition_result}")
        
        # Note: In a real Python script, you would branch execution here using 'if condition_result:'
        # This flat structure executes all nodes, but in FlowGen logic, it routes edges.
`;
        break;

      case NodeType.JAVASCRIPT:
        code += `        # JavaScript Node - Logic requires manual Python implementation
        # Original JS Code:
        """
${config.code || '// No code provided'}
        """
        # TODO: Translate the above JS logic to Python here
        output = input_data 
`;
        break;

      case NodeType.HTTP_REQUEST:
        const method = config.method || 'GET';
        const url = config.url || 'https://api.example.com';
        code += `        # HTTP Request
        response = requests.request("${method}", "${url}", json=input_data)
        try:
            output = response.json()
        except:
            output = {"text": response.text}
`;
        break;

      case NodeType.DEBUG:
        code += `        # Debug / Output inspection
        print(f"🐞 Debug [${label}]: {json.dumps(input_data, indent=2)}")
        output = input_data
`;
        break;
        
      default:
        code += `        output = input_data\n`;
    }

    code += `        results['${safeId}'] = output
        print(f"✅ Node '${label}' completed.")
    except Exception as e:
        print(f"❌ Node '${label}' failed: {e}")
        results['${safeId}'] = {"error": str(e)}

`;
  });

  code += `    print("🏁 Workflow Finished.")
    return results

if __name__ == "__main__":
    run_workflow()
`;

  return code;
};